"""Tests for magi_gui.report module"""
from datetime import datetime
from typing import Dict
from unittest.mock import MagicMock, patch

import pytest

from magi.models import (
    ConsensusResult,
    DebateRound,
    Decision,
    PersonaType,
    ThinkingOutput,
    VoteOutput,
)
from magi_gui.report import (
    ReportGenerator,
    generate_report,
    generate_filename,
    PERSONA_LABELS,
    PERSONA_ORDER,
    DECISION_LABELS,
)


class TestReportGenerator:
    """Tests for ReportGenerator class"""

    def test_generate_returns_complete_report(self, mock_consensus_result):
        """generate() should return a complete Markdown report"""
        generator = ReportGenerator(mock_consensus_result, "Test prompt")
        
        report = generator.generate()
        
        assert "# MAGI System 合議結果レポート" in report
        assert "## 入力" in report
        assert "Test prompt" in report
        assert "## Thinking Phase" in report
        assert "## Debate Phase" in report
        assert "## Voting Phase" in report
        assert "## Final Decision" in report
        assert "Generated by MAGI GUI" in report

    def test_header_section(self, mock_consensus_result):
        """_header() should return the report title"""
        generator = ReportGenerator(mock_consensus_result, "Test prompt")
        
        header = generator._header()
        
        assert header == "# MAGI System 合議結果レポート"

    def test_input_section(self, mock_consensus_result):
        """_input_section() should include the prompt in code block"""
        generator = ReportGenerator(mock_consensus_result, "My test prompt")
        
        section = generator._input_section()
        
        assert "## 入力" in section
        assert "```" in section
        assert "My test prompt" in section

    def test_thinking_section_includes_all_personas(
        self, mock_consensus_result, mock_thinking_results
    ):
        """_thinking_section() should include all three personas"""
        generator = ReportGenerator(mock_consensus_result, "Test prompt")
        
        section = generator._thinking_section()
        
        assert "### MELCHIOR" in section
        assert "### BALTHASAR" in section
        assert "### CASPER" in section
        assert "MELCHIOR analysis" in section
        assert "BALTHASAR analysis" in section
        assert "CASPER analysis" in section

    def test_thinking_section_handles_missing_output(self, mock_consensus_result):
        """_thinking_section() should handle missing persona output"""
        # Remove one persona's output
        mock_consensus_result.thinking_results.pop(PersonaType.CASPER, None)
        generator = ReportGenerator(mock_consensus_result, "Test prompt")
        
        section = generator._thinking_section()
        
        assert "*No output produced.*" in section

    def test_debate_section_includes_rounds(
        self, mock_consensus_result, mock_debate_round
    ):
        """_debate_section() should include debate rounds"""
        generator = ReportGenerator(mock_consensus_result, "Test prompt")
        
        section = generator._debate_section()
        
        assert "## Debate Phase" in section
        assert "### Round 1" in section
        assert "#### MELCHIOR" in section
        assert "#### BALTHASAR" in section
        assert "#### CASPER" in section

    def test_debate_section_handles_empty_results(self, mock_consensus_result):
        """_debate_section() should handle empty debate results"""
        mock_consensus_result.debate_results = []
        generator = ReportGenerator(mock_consensus_result, "Test prompt")
        
        section = generator._debate_section()
        
        assert "*No debate rounds were produced.*" in section

    def test_voting_section_includes_table(
        self, mock_consensus_result, mock_voting_results
    ):
        """_voting_section() should include voting table"""
        generator = ReportGenerator(mock_consensus_result, "Test prompt")
        
        section = generator._voting_section()
        
        assert "## Voting Phase" in section
        assert "| Persona | Vote | Reason | Conditions |" in section
        assert "MELCHIOR" in section
        assert "APPROVE" in section.upper()

    def test_voting_section_escapes_pipe_characters(self, mock_consensus_result):
        """_voting_section() should escape pipe characters in content"""
        # Add a reason with pipe character
        mock_consensus_result.voting_results[PersonaType.MELCHIOR].reason = "Test | with pipe"
        generator = ReportGenerator(mock_consensus_result, "Test prompt")
        
        section = generator._voting_section()
        
        assert "Test \\| with pipe" in section

    def test_decision_section_approved(self, mock_consensus_result):
        """_decision_section() should show APPROVED status"""
        mock_consensus_result.final_decision = Decision.APPROVED
        generator = ReportGenerator(mock_consensus_result, "Test prompt")
        
        section = generator._decision_section()
        
        assert "## Final Decision" in section
        assert "✅ APPROVED" in section

    def test_decision_section_denied(self, mock_consensus_result):
        """_decision_section() should show DENIED status"""
        mock_consensus_result.final_decision = Decision.DENIED
        generator = ReportGenerator(mock_consensus_result, "Test prompt")
        
        section = generator._decision_section()
        
        assert "❌ DENIED" in section

    def test_decision_section_conditional_with_conditions(self, mock_consensus_result):
        """_decision_section() should show CONDITIONAL with conditions"""
        mock_consensus_result.final_decision = Decision.CONDITIONAL
        mock_consensus_result.all_conditions = ["Condition 1", "Condition 2"]
        generator = ReportGenerator(mock_consensus_result, "Test prompt")
        
        section = generator._decision_section()
        
        assert "⚠️ CONDITIONAL" in section
        assert "### Conditions" in section
        assert "- Condition 1" in section
        assert "- Condition 2" in section

    def test_footer_includes_timestamp(self, mock_consensus_result):
        """_footer() should include generation timestamp"""
        generator = ReportGenerator(mock_consensus_result, "Test prompt")
        
        footer = generator._footer()
        
        assert "---" in footer
        assert "Generated by MAGI GUI at" in footer
        # Check timestamp format (YYYY-MM-DD HH:MM:SS)
        import re
        assert re.search(r"\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}", footer)


class TestGenerateReport:
    """Tests for generate_report convenience function"""

    def test_returns_markdown_string(self, mock_consensus_result):
        """generate_report() should return a Markdown string"""
        report = generate_report(mock_consensus_result, "Test prompt")
        
        assert isinstance(report, str)
        assert "# MAGI System 合議結果レポート" in report


class TestGenerateFilename:
    """Tests for generate_filename function"""

    def test_returns_markdown_extension(self):
        """generate_filename() should return .md extension"""
        filename = generate_filename("Test prompt")
        
        assert filename.endswith(".md")

    def test_includes_magi_prefix(self):
        """generate_filename() should include 'magi-report' prefix"""
        filename = generate_filename("Test prompt")
        
        assert filename.startswith("magi-report-")

    def test_includes_timestamp(self):
        """generate_filename() should include timestamp"""
        timestamp = datetime(2026, 1, 8, 15, 30, 45)
        
        filename = generate_filename("Test prompt", timestamp)
        
        assert "20260108-153045" in filename

    def test_uses_current_time_by_default(self):
        """generate_filename() should use current time when no timestamp provided"""
        filename1 = generate_filename("Test")
        filename2 = generate_filename("Test")
        
        # Both should have today's date
        today = datetime.now().strftime("%Y%m%d")
        assert today in filename1
        assert today in filename2
